general {
  background      = "0xFF1E1E2E"
  base            = "0xFF1E1E2E"
  text            = "0xFFCDD6F4"
  accent          = "0xFFCBA6F7"
  font_size       = "14"
  small_font_size = "12"
  font_family     = "JetBrains Nerd Font"
  rounding_large  = 16
  rounding_small  = 8
}
